### ISSUE TITLE
Looks like it's not working if width isn't specified

### ISSUE THREAD

**Issue by SiamKreative** [meandmax/lory#21]
When I copied the markup + Prerequisted CSS styles from the demo page, slider didn't work. It seems to be because in the demo you actually specify a fixed width for the `li` element.

```css
.simple li {
	width: 270px;
	margin-right: 10px;
}
@media screen and (min-width: 640px ) {
	.simple li {
		width: 580px;
	}
}
@media screen and (min-width: 980px ) {
	.simple li {
		width: 880px;
	}
}
```

So my question is... is there a way to make it work out of the box, without specifying a width? I feel like it's a bit annoying to specify a fixed width in a responsive context.
