### ISSUE TITLE
Centre mode

### ISSUE THREAD

**Issue by SukhKalsi** [meandmax/lory#460]
Hello

How can i configure Lory to centre the slide?

For example, Slick has an option called 'centerMode' which enables me to show one slide only but with mini previews of the previous and next slide.

Thanks

**Comment by nstanard** [comment]
You would probably want to use variable width mode.

**Comment by SukhKalsi** [comment]
Hmm not sure how that helps? Lory seems to always position the slides to the hard edge (either left or right depending on direction)

**Comment by nstanard** [comment]
Seems like you realize that this isn't an option currently ;)

**Comment by SukhKalsi** [comment]
Ha I guess so! So I suppose this is a feature request. What is the effort level required to get this in?

**Comment by curtisblackwell** [comment]
Any plans for this yet?

**Comment by curtisblackwell** [comment]
I figured out a way to accomplish this using CSS.

Let's say you want 3 slides displayed at a time. Each slide is 200px, and there's a 20px gutter b/w slides.

```scss
$slideWidth: 200px;
$slideGutter: 20px;

.frame {
  width: ($slideWidth * 3) + ($slideGutter * 2);
}

.slide {
  transform: translateX($slideWidth + $slideGutter);
  width: $slideWidth;

  + .slide {
    margin-left: $slideGutter;
  }
}
```

```js
lory(slider, { infinite: 3 });
```
